import type { Metadata } from "next";
import Link from "next/link";
import { Target, Compass, ShieldCheck, Handshake, Lightbulb, CheckCircle2 } from "lucide-react";

export const metadata: Metadata = { title: "Quem somos", description: "Conheça a OFFSEA, fornecedora de materiais e equipamentos para a indústria e operações offshore e onshore.", alternates: { canonical: "/quemsomos" } };

export default function About() {
  return <main id="conteudo"><section className="about-hero"><div className="container"><p className="eyebrow light">QUEM SOMOS</p><h1>Conhecer sua demanda.<br /><span>Conectar soluções.</span></h1><p>Somos a OFFSEA. Uma empresa de suprimentos industriais que entende a importância de cada material para a continuidade da sua operação.</p></div></section><section className="section"><div className="container about-story"><div className="about-photo"><img src="/images/industrial.webp" alt="Estrutura industrial" width="1100" height="1000" /></div><div><p className="eyebrow">NOSSA ESSÊNCIA</p><h2>Materiais certos.<br />Relações de confiança.</h2><p>Atendemos demandas de materiais e equipamentos para a indústria, construção e operações offshore e onshore. Nosso trabalho parte de uma escuta atenta: entender a aplicação, os requisitos técnicos e a necessidade de cada cliente.</p><p>De componentes para manutenção a materiais para novos projetos, buscamos reunir diferentes linhas de fornecimento com atendimento consultivo e comunicação direta.</p><Link href="/#produtos" className="text-link">Explore nossas linhas de fornecimento</Link></div></div></section><section className="principles section"><div className="container"><div className="principles-grid"><article><Target aria-hidden="true" /><p className="eyebrow">MISSÃO</p><h2>Contribuir para uma<br />operação contínua.</h2><p>Fornecer materiais e soluções que apoiem a segurança e a produtividade dos clientes, com atenção técnica e atendimento próximo.</p></article><article><Compass aria-hidden="true" /><p className="eyebrow">VISÃO</p><h2>Ser uma referência<br />em confiança.</h2><p>Construir relações duradouras e ser reconhecida pela qualidade do atendimento e pela consistência no fornecimento de suprimentos industriais.</p></article></div></div></section><section className="section values"><div className="container"><p className="eyebrow">VALORES QUE ORIENTAM NOSSO TRABALHO</p><h2>Compromisso em cada detalhe.</h2><div className="values-grid">{[{ Icon: ShieldCheck, name: "Ética e responsabilidade", text: "Transparência na comunicação e respeito aos compromissos assumidos." }, { Icon: CheckCircle2, name: "Excelência", text: "Atenção às especificações e aos detalhes de cada solicitação." }, { Icon: Handshake, name: "Foco no cliente", text: "Entender a operação para buscar soluções adequadas à necessidade." }, { Icon: Lightbulb, name: "Inovação", text: "Acompanhar tecnologias e formas de tornar o fornecimento mais eficiente." }].map(({ Icon, name, text }) => <article key={name}><Icon aria-hidden="true" /><h3>{name}</h3><p>{text}</p></article>)}</div></div></section><section className="about-cta"><div className="container"><div><p className="eyebrow light">VAMOS CONVERSAR</p><h2>O próximo passo começa<br />com a sua demanda.</h2></div><Link className="button button-cyan" href="/#cotacao">Solicitar cotação</Link></div></section></main>;
}
